FileExplorer.svelte
Settings.svelte
TaskManager.svelte
Terminal.svelte
ControlPanel.svelte
SystemInfo.svelte
Update.svelte
Store.svelte
Notepad.svelte
WordPad.svelte
Calculator.svelte
Calendar.svelte
Clock.svelte
Notes.svelte
SnippingTool.svelte
Browser.svelte
Mail.svelte
Chat.svelte
Weather.svelte
Maps.svelte
Paint.svelte
MediaPlayer.svelte
PhotoViewer.svelte
Camera.svelte
Solitaire.svelte
Minesweeper.svelte
Chess.svelte
CodeEditor.svelte
Logs.svelte
About.svelte
